sudo: required

language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  - jq ".accessKeyId |= \"$AWS_ID\" | .secretAccessKey |= \"$AWS_SECRET\" | .s3.bucket |= \"$S3_BUCKET\" | .cloudfront.url |= \"$CLOUDFRONT_URL\"" credentials.tmpl.json > credentials.json
  - ls -l credentials.json

script:
  - grunt deploy

after_success:
  - grunt release
